### ISSUE TITLE
[Bug]: Renogy PGH1 Inverter API error

### ISSUE THREAD

**Issue by Anto79-ops** [firstof9/ha-renogy#11]
### The problem

hey,

I have  the 1000 W Renogy Pure Sine Wave Invter (RINVTPGH110111S)) connected to the ONE Core Hub. Works well on the app and hub, for example:

![image](https://github.com/user-attachments/assets/37aaff57-1495-45ca-8b13-8fb77da5bbc7)

However, it seems only the conectivity entites are provided via the API:

![image](https://github.com/user-attachments/assets/71108d0e-9888-4b5f-abb5-d899bf25bff9)

and none of the sensors like load, mode, voltage, temp, watts etc.

Renogy has been contacted about this, because its the API that does not return those values and leads to these errors:

```
This error originated from a custom integration.

Logger: renogyapi
Source: custom_components/renogy/__init__.py:154
integration: Renogy (documentation, issues)
First occurred: 11:35:41 AM (130 occurrences)
Last logged: 12:08:47 PM

An error reteiving data from the server, code: 500 message: {'type': 'network_anomaly', 'msg': 'Network anomaly, please try again later!'}
No data in API response.
```

and as you tested, via API, it returns this:

```
{
    "type": "network_anomaly",
    "msg": "Network anomaly, please try again later!"
}
```

So hopefully Renogy does some backend changed to this model inverter so that it can work with the integration.

Cheers,

### What version of Home Assistant?

2024.12.3

### What version of Renogy?

1.0.0-b4

**Comment by Anto79-ops** [comment]
Looks like renogy added the sensors for the inverter, but they appear as `unknown`

![image0.jpg](https://github.com/user-attachments/assets/6fd87e6b-c722-4968-818f-aaace8c37cdc)

Hers diag for the inverter

**Comment by Anto79-ops** [comment]
i put the inverter into Eco Mode, but nothing changed on the api side. So not sure now what output 1 means:

```
   },
    "4674937632304311881": {
      "deviceId": "4674937632304311881",
      "name": "Inverter",
      "mac": "32",
      "firmware": "0100.0102.0202",
      "status": "online",
      "connection": "RS485",
      "serial": "",
      "model": "RINVTPGH110111S",
      "data": {
        "auxiliaryBatteryTemperature": null,
        "acOutputHz": 60.0,
        "ueiVolts": null,
        "outputVolts": 113.400002,
        "loadAmps": null,
        "solarWatts": null,
        "chargePriority": null,
        "output": 1,
        "ueiAmps": null,
        "loadWattsMode": null,
        "loadActiveWatts": 41,
        "solarChargingVolts": null,
        "temperature": 22.0,
        "loadWatts": null,
        "outputAmps": 370.0,
        "sku": "RINVTPGH110111S",
        "solarChargingAmps": null,
        "batteryType": null,
        "batteryVolts": 12.6
      }
```

**Comment by Anto79-ops** [comment]
thanks @firstof9 looks pretty good, I can now see updates to the inverter!

![image](https://github.com/user-attachments/assets/b37ba15c-62be-49a4-9117-2efefcc533d1)


a couple of logs on startup, with a greyed out entity:

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:608
integration: Sensor (documentation, issues)
First occurred: 10:00:34 AM (2 occurrences)
Last logged: 10:00:34 AM

Error adding entity sensor.inverter_charge_priority for domain sensor with platform renogy
Error adding entity sensor.inverter_output for domain sensor with platform renogy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 295, in async_internal_added_to_hass
    raise HomeAssistantError(
        f"Entity {self.entity_id} cannot be added as the entity category is set to config"
    )
homeassistant.exceptions.HomeAssistantError: Entity sensor.inverter_charge_priority cannot be added as the entity category is set to config
```

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/renogy/sensor.py:98
integration: Renogy (documentation, issues)
First occurred: 10:00:57 AM (2 occurrences)
Last logged: 10:00:57 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1552, in _async_process_registry_update_or_remove
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 557, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/renogy/sensor.py", line 98, in native_value
    value = OUTPUT_MODES[data[self._type]]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 1
```
